name: Bug Report
description: Something isn't working as expected
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues
          required: true
        - label: I have read the installation guide
          required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Create VideoEncoder with config...
        2. Encode frames...
        3. See error...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js version
      placeholder: "20.10.0"
    validations:
      required: true

  - type: input
    attributes:
      label: node-webcodecs version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: envinfo
    attributes:
      label: Environment info
      description: |
        Run: `npx envinfo --system --binaries --npmPackages=node-webcodecs`
      render: shell
