name: Question
description: Ask a question about using node-webcodecs
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening an issue, please check:
        1. The [README documentation](https://github.com/pproenca/node-webcodecs#readme)
        2. [Existing issues](https://github.com/pproenca/node-webcodecs/issues?q=is%3Aissue)
        3. [Stack Overflow](https://stackoverflow.com/questions/tagged/webcodecs)

  - type: checkboxes
    id: prereqs
    attributes:
      label: Prerequisites
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched for existing issues and discussions
          required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe what you're trying to accomplish
      placeholder: I'm trying to...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code example
      description: Relevant code snippet (if applicable)
      render: typescript
    validations:
      required: false

  - type: textarea
    id: tried
    attributes:
      label: What I've tried
      description: List approaches you've already attempted
      placeholder: |
        1. I tried...
        2. I also looked at...
    validations:
      required: false

  - type: textarea
    id: envinfo
    attributes:
      label: Environment info
      description: |
        Run: `npx envinfo --system --binaries --npmPackages=node-webcodecs`
      render: shell
    validations:
      required: false
